name: ai-model
replicaCount: 1
image:
  repository: tensorflow/serving
  tag: latest
containerPort: 8501
service:
  type: ClusterIP
  port: 80
serviceAccount:
  create: true             # Whether to create the ServiceAccount
  automount: true          # Whether to automatically mount the ServiceAccount token
  annotations: {}          # Optional annotations for the ServiceAccount

