{{- if or (.Values.serviceAccount.create | default false) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-deployment.serviceAccountName" . }}
  labels:
    {{- include "ai-deployment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
